# Generated by Django 4.2.7 on 2024-06-26 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customerRoles', to='api.role'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ownerRoles', to='api.role'),
        ),
    ]
